version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine
    restart: "no"
    environment:
      POSTGRES_DB: perryquotes
      POSTGRES_USER: perry
      POSTGRES_PASSWORD: changeit
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"