INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Perry Rhodan - Das größte Abenteuer','DGA',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Die Dritte Macht','SB1',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Das Mutanten-Korps','SB2',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Der Unsterbliche','SB3',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Der kosmische Lockvogel','SB4',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Vorstoß nach Arkon','SB5',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Der Robotregent','SB6',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Atlan','SB7',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Festung Atlantis','SB8',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Das rote Universum','SB9',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Thora','SB10',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Der Fall Kolumbus','SB11',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Der Anti','SB12',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Der Zielstern','SB13',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Rhodans Sohn','SB14',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Mechanica','SB15',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Die Posbis','SB16',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Die Hundertsonnenwelt','SB17',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Hornschrecken','SB18',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Das zweite Imperium','SB19',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Kampf gegen die Blues','SB20',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Straße nach Andromeda','SB21',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Schrecken der Hohlwelt','SB22',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Die Maahks','SB23',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Die Para-Sprinter','SB24',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Brennpunkt Andro-Beta','SB25',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Kontrollstation Modul','SB26',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Andromeda','SB27',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO public.book_source(uuid,name,shortcut,created_at,last_modified_at,version) VALUES(gen_random_uuid(),'Lemuria','SB28',CURRENT_DATE,CURRENT_DATE,1);